global:
  scrape_interval: 10s # when Prometheus is pulling data from exporters etc
  evaluation_interval: 20s # time between each evaluation of Prometheus' alerting rules

scrape_configs:
  - job_name: script
    static_configs:
      - targets:
        - script:8000